version: '2'
services:
  postgres:
    image: postgres:10.21
    ports:
      - 5432:5432
    volumes: 
      - ./postgres_data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=58877216/Abca1373
      - POSTGRES_USER=odoo14
